// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIrdhtLW1pdkIHGufb3cbd8YiUdyyo45Y',
    appId: '1:1019201145549:web:be4b4e814d8fb52167f784',
    messagingSenderId: '1019201145549',
    projectId: 'expense-tracker-701a4',
    authDomain: 'expense-tracker-701a4.firebaseapp.com',
    storageBucket: 'expense-tracker-701a4.appspot.com',
    measurementId: 'G-NC1S72SX6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Mm6-9dWvss11spFFSomXQqHEHDazJSc',
    appId: '1:1019201145549:android:c59321bab5eef44b67f784',
    messagingSenderId: '1019201145549',
    projectId: 'expense-tracker-701a4',
    storageBucket: 'expense-tracker-701a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9wmNZvqCRhydY3bzPlZGkdXsrjBs4LIY',
    appId: '1:1019201145549:ios:058963c8a6e784b867f784',
    messagingSenderId: '1019201145549',
    projectId: 'expense-tracker-701a4',
    storageBucket: 'expense-tracker-701a4.appspot.com',
    iosClientId: '1019201145549-9p9k31ecomr5rcl7t9e21tq49906t89u.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9wmNZvqCRhydY3bzPlZGkdXsrjBs4LIY',
    appId: '1:1019201145549:ios:058963c8a6e784b867f784',
    messagingSenderId: '1019201145549',
    projectId: 'expense-tracker-701a4',
    storageBucket: 'expense-tracker-701a4.appspot.com',
    iosClientId: '1019201145549-9p9k31ecomr5rcl7t9e21tq49906t89u.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
